global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'windows'
    static_configs:
      - targets:
          - '10.180.16.227:9182'
        labels:
          environment: 'local'
          team: 'platform'
          ip: '10.180.16.227'

  - job_name: 'apache'
    static_configs:
      - targets: ['apache-exporter:9117']
        labels:
          environment: 'local'
          team: 'platform'

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql-exporter:9104']
        labels:
          environment: 'local'
          team: 'platform'
          ip: '192.168.0.4'
  - job_name: 'mssql'
    static_configs:
      - targets: ['mssql-exporter:4000']
        labels:
            environment: 'local'
            team: 'platform'
            ip: '10.30.3.4'

  - job_name: 'php-application'
    metrics_path: /metrics
    static_configs:
      - targets: ['php-apache:80']

